export default {
  SET_READY: 'SET_READY',
  SET_PROGRESS: 'SET_PROGRESS',
  SET_ASSETS: 'SET_ASSETS',
  ADD_CORRECT_QUESTION_NUMBER: 'ADD_CORRECT_QUESTION_NUMBER',
  ADD_CURRENT_QUESTION_NUMBER: 'ADD_CURRENT_QUESTION_NUMBER'
}
